# Generated by Django 4.1.5 on 2023-03-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offPer',
            field=models.CharField(default='', max_length=15),
        ),
    ]
