# Generated by Django 4.1.5 on 2023-03-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_orders_razorpaypaymentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='paymentstatus',
            field=models.CharField(default='', max_length=255),
        ),
    ]
