# Generated by Django 4.1.5 on 2023-03-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_orders_oid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='razorpayid',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='razorpaypaymentid',
            new_name='razorpay_payment_id',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='razorpaysignature',
            new_name='razorpay_signature',
        ),
    ]
