# Generated by Django 4.1.5 on 2023-04-01 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_rename_razorpayid_orders_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amountpaid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='oid',
        ),
    ]
