# Generated by Django 4.1.5 on 2023-04-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_orders_amountpaid_remove_orders_oid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_amount',
            field=models.IntegerField(default=0),
        ),
    ]
